version: '3.3'
services:
  db:
    image: mysql:8.0.29
    command:
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_0900_ai_ci'
      - '--sql-mode=NO_ENGINE_SUBSTITUTION'
      - '--log-bin-trust-function-creators=1'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123rootPass1'
      MYSQL_DATABASE: 'db_qa'
      MYSQL_USER: 'user_qa'
      MYSQL_PASSWORD: 'P4ssword!!'
    logging:
      options:
        max-size: 5m
